<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_List name_list-name</name>
   <tag></tag>
   <elementGuidId>083db81e-7ad9-4a49-9fcd-5806e4ecbaed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='list-name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#list-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e33e58ca-9cd7-483c-8219-64806618cb1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d978449e-91f6-49bf-af4a-5709534daa3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>258883c2-e5a2-49a0-ad92-5fad4220c3be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Shopping List 1</value>
      <webElementGuid>e195c209-5b1e-4bac-b82c-fab2e5d66b8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>list-name</value>
      <webElementGuid>2268ad38-3390-49c4-94dd-6b834ab46ff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>list-name</value>
      <webElementGuid>13ea6bbb-e622-46be-b81d-f70b592bae64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-input-text fix-width-x-large</value>
      <webElementGuid>3fffdb1d-2104-4d8c-b00e-bff640bf0968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list-name&quot;)</value>
      <webElementGuid>b93eb0d5-47bd-4e23-9d4e-fd802a672605</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='list-name']</value>
      <webElementGuid>24d12576-734e-414b-acfc-fee1df997b72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='create-list-form']/div[2]/div/span/input</value>
      <webElementGuid>f31fda93-4718-4128-ad0e-3f8c0f5a0b6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/input</value>
      <webElementGuid>15ede383-c96b-4fab-a339-efba3b388174</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'list-name' and @name = 'list-name']</value>
      <webElementGuid>26806c29-5d99-401a-afd3-7b07c962c886</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
