<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Add to List_wishListDropDown</name>
   <tag></tag>
   <elementGuidId>1c798571-2798-4294-aff3-c6bfdeb69ab5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='wishListDropDown']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wishListDropDown</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f88702b8-ed02-455a-8d14-1c72db056e01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wishListDropDown</value>
      <webElementGuid>d41e63c1-a0bd-470b-9c11-ce80078a3314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button a-button-dropdown a-button-grouplast a-spacing-none a-button-base wishlist-dropdown-button</value>
      <webElementGuid>99693e87-e51f-45d2-b316-16117a0fc4b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>2f17bb37-45a3-4b9a-acc2-cacc684b3187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-posinset</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>281a5919-434b-4fd7-af7d-d44516177eaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-setsize</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>f6e35a61-4337-4451-a80e-eb484911f4a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wishListDropDown&quot;)</value>
      <webElementGuid>12903b4f-e0b1-4b19-8588-b09e13da5a79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='wishListDropDown']</value>
      <webElementGuid>8a47c15a-584b-4269-ad52-5fbb58bfe7ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add-to-wishlist-button-group']/span[2]</value>
      <webElementGuid>509810a2-d985-4f6a-a903-1e641dda4e11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[3]/div/span[2]</value>
      <webElementGuid>03a6ba40-e2b1-45d7-8bfd-7025d902f5cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'wishListDropDown']</value>
      <webElementGuid>e5ff95c1-d286-417a-bbbd-f766fccd5b83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
