<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Add to List</name>
   <tag></tag>
   <elementGuidId>89aea2e8-ce9a-42e4-9935-84d7aa2f6120</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='wishListMainButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wishListMainButton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6f269493-d4d2-4621-a830-4025ecba7f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wishListMainButton</value>
      <webElementGuid>2c967115-40cb-4a59-9982-9653e6798d8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button a-button-groupfirst a-spacing-none a-button-base a-declarative</value>
      <webElementGuid>41377f05-404d-4048-bfa6-efbec5766404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>99eb1aab-6748-49f1-8827-cfd6fc7af0e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>add-wishlist-declarative</value>
      <webElementGuid>09ff164f-6479-4e44-8275-7461e1b419ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-posinset</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>4d856d01-ced2-47d2-8f6f-65c4ed143ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-setsize</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>1d05a0fa-4767-4911-8ea1-bad85a11ca87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 
                    Add to List    
            </value>
      <webElementGuid>c5a66b89-d660-4d80-9c8a-3a3256c2932a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wishListMainButton&quot;)</value>
      <webElementGuid>7c13fb8b-ad1f-4a0e-a147-2eec599b239c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='wishListMainButton']</value>
      <webElementGuid>a5d7a3c4-77ee-4cd0-9585-85c62a4d5d61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add-to-wishlist-button-group']/span</value>
      <webElementGuid>23cb91c5-6c1d-41df-a60f-0d2ff6ebf0eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[3]/div/span</value>
      <webElementGuid>02df27fa-f3ae-4224-bfa9-fb6ac3271197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'wishListMainButton' and (text() = ' 
                    Add to List    
            ' or . = ' 
                    Add to List    
            ')]</value>
      <webElementGuid>952a4ff7-b27e-4b8d-a9c8-da01ead925b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
