<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Australia</name>
   <tag></tag>
   <elementGuidId>a66ea297-21d3-4cdc-a0df-b98c2ab95dbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='icp-dropdown_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#icp-dropdown_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1b00ca71-aad8-4d0f-ab3e-fa232a504b51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>e38cdebb-55d3-44c8-98f1-957280c2f509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>9e518dda-62ec-47b2-9aa6-d84a6cf201bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ebb7493c-7f58-42cf-9ecb-159da6136c04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>{&quot;stringVal&quot;:&quot;https://www.amazon.com.au/?ref_=icp_country_from_us&quot;}</value>
      <webElementGuid>f6c526a8-15be-42fb-b5af-80a0a58baa01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>icp-dropdown_0</value>
      <webElementGuid>e7d18f2e-199a-43ad-8157-8a23ddcc2f7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-dropdown-link</value>
      <webElementGuid>ff52dc2f-b5c5-4b96-84a0-369729d427e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Australia</value>
      <webElementGuid>187ed342-4dbf-403a-a091-94b1075853bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;icp-dropdown_0&quot;)</value>
      <webElementGuid>95448db7-6664-472d-ac68-b6e6b9616ded</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='icp-dropdown_0']</value>
      <webElementGuid>fc691d11-511d-4b20-b81a-592a6948244c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='icp-dropdown-item-0']/a</value>
      <webElementGuid>20450d6f-d66c-4c32-9a78-dc57e563acb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Australia')]</value>
      <webElementGuid>f0d65e97-263b-482c-bdb7-201755bd2744</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[6]</value>
      <webElementGuid>60bd7cef-6a23-4ea1-aa0e-869122944c7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/ul/li/a</value>
      <webElementGuid>7aaae7e1-19d5-4ff3-8e86-0618f84fcaf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and @id = 'icp-dropdown_0' and (text() = ' Australia' or . = ' Australia')]</value>
      <webElementGuid>8b782ee3-9d5b-4aea-ad17-606ff05737c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
